dataset:

  train_images: data/train/images
  train_masks: data/train/masks

  vadataset:

  train_images: data/train/images
  train_masks: data/train/masks

  val_images: data/val/images
  val_masks: data/val/masks

  test_images: data/val/images


model:

  num_classes: 1


training:

  epochs: 20
  batch_size: 4
  learning_rate: 0.0001


output:

  checkpoint_dir: runs/checkpoints
  results_dir: runs/results
