dataset:
  train_images: data/train/images
  train_masks: data/train/masks
  val_images: data/val/images
  val_masks: data/val/masks
  test_images: data/testImages/images

model:
  num_classes: 1

training:
  batch_size: 4
  lr: 0.0001
  epochs: 50

output:
  checkpoint_dir: runs/checkpoints
  log_dir: runs/logs
  results_dir: runs/results
